// Bake Baidu result HTML snapshot into a TS module so we can delete public/www.baidu.com2
// Usage: node scripts/bakeBaiduResult.js
// It reads public/www.baidu.com2/www.baidu.com/s.html and writes src/constants/skin2ResultSnapshot.ts
// - Extracts <link rel="stylesheet"> hrefs and <style> contents in <head>
// - Removes all <script> tags
// - Captures <body> innerHTML
// Note: Re-run if the source changes.

const fs = require('fs');
const path = require('path');

function readFileSafe(p) {
  try {
    return fs.readFileSync(p, 'utf8');
  } catch (e) {
    return null;
  }
}

function ensureDir(dir) {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
}

function escapeForTemplateLiteral(str) {
  return String(str).replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

(function main() {
  const repoRoot = process.cwd();
  const source = path.join(repoRoot, 'public', 'www.baidu.com2', 'www.baidu.com', 's.html');
  const outDir = path.join(repoRoot, 'src', 'constants');
  const outFile = path.join(outDir, 'skin2ResultSnapshot.ts');

  const html = readFileSafe(source);
  if (!html) {
    console.error('Source HTML not found:', source);
    process.exit(1);
  }

  const headMatch = html.match(/<head[\s\S]*?>[\s\S]*?<\/head>/i);
  const bodyMatch = html.match(/<body[\s\S]*?>([\s\S]*?)<\/body>/i);
  const headContent = headMatch ? headMatch[0] : '';
  const bodyInner = bodyMatch ? bodyMatch[1] : '';

  const scrubScripts = (s) => s.replace(/<script[\s\S]*?<\/script>/gi, '');
  const headNoScripts = scrubScripts(headContent);
  const bodyNoScripts = scrubScripts(bodyInner);

  const cssLinks = [];
  const linkRegex = /<link[^>]*rel=["']?stylesheet["']?[^>]*>/gi;
  const hrefRegex = /href=["']([^"']+)["']/i;
  const links = headNoScripts.match(linkRegex) || [];
  for (const tag of links) {
    const m = tag.match(hrefRegex);
    if (m && m[1]) cssLinks.push(m[1]);
  }

  const inlineStyles = [];
  const styleRegex = /<style[\s\S]*?>([\s\S]*?)<\/style>/gi;
  let sm;
  while ((sm = styleRegex.exec(headNoScripts))) {
    inlineStyles.push(sm[1] || '');
  }

  ensureDir(outDir);
  const ts = '/* Auto-generated by scripts/bakeBaiduResult.js */\n'
    + 'export const skin2ResultCssLinks: string[] = ' + JSON.stringify(cssLinks, null, 2) + ';\n'
    + 'export const skin2ResultInlineStyles: string[] = [\n'
    + inlineStyles.map(s => '  `'+escapeForTemplateLiteral(s)+'`').join(',\n') + '\n];\n'
    + 'export const skin2ResultBodyHtml: string = `\n'
    + escapeForTemplateLiteral(bodyNoScripts) + '\n`;\n';

  fs.writeFileSync(outFile, ts, 'utf8');
  console.log('Wrote snapshot:', outFile);
})();